[tool.poetry]
name = "lignam-sample"
version = "0.1.0"
description = ""
authors = ["aoda"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
lingam = "^1.8.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
